# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  timeout: 5000

development:
  <<: *default
  database: ld-development
  host: localhost
  username: root
  password: root
  port: 5432


production:
  <<: *default
  database: ld-development
  host: localhost
  username: root
  password: root
  port: 5432