# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 781e18e318f39d11df1a1e32f6e6a95793026e3fd7e98eaedf3d7834e92bb194f12789fd21574f9bccc79947335a73967316c2d9f75a17dbc793dcdd81dbab4f

test:
  secret_key_base: c3c58d881a617a83ddde1b001df52bb9d1d4e46e0a5a7276c4e4a24459b7f7fcde9b11da0a97dafd233b0406391de0f76569b4ea5ff63265ec9103013aabc7ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
